# =========================
# Stage 1 - Build
# =========================
FROM maven:3.8.6-openjdk-8-slim AS build

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone -b Master https://github.com/abdelrahmanonline4/sourcecodeseniorwr.git .

RUN mvn clean package -DskipTests

# =========================
# Stage 2 - Runtime
# =========================
FROM tomcat:9.0-jdk8-temurin

RUN rm -rf /usr/local/tomcat/webapps/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/ROOT.war

RUN groupadd -r tomcat && \
    useradd -r -g tomcat tomcat && \
    chown -R tomcat:tomcat /usr/local/tomcat

USER tomcat

EXPOSE 8080

HEALTHCHECK CMD curl -f http://localhost:8080 || exit 1

CMD ["catalina.sh","run"]
